name: Stats

on:
  push: 
    branches: [ main ]

jobs:
  build: 
    runs-on: ubuntu-lastest

    steps: 
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup pyhon
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Run script
        run: python ./Roadmap/stats.py

      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update stats
          commit_user_name: julian.lara
          commit_user_email: julian.lara@test.com
          commit_author: julian.lara
